<template>
    <transition name="workspace-fade">
        <div v-if="show" class="pointer-events-none absolute inset-0 z-40 font-['Noto_Sans_SC']">
            <div class="pointer-events-none absolute left-8 top-36 w-[28rem] max-h-[54.5rem]">
            <section class="tech-panel-enhanced pointer-events-auto relative flex max-h-[54.5rem] flex-col overflow-hidden p-5" style="clip-path: polygon(0 0,100% 0,100% 95%,92% 100%,0 100%);">
                <div class="absolute left-0 top-0 h-[2px] w-full animate-pulse bg-gradient-to-r from-transparent via-cyan-400 to-transparent"></div><div class="corner-decoration corner-tl scale-125"></div><div class="corner-decoration corner-tr scale-125"></div>
                <div class="mb-4 flex items-center border-b-2 border-cyan-500/40 pb-3"><div class="mr-3 h-6 w-1.5 bg-yellow-400 shadow-[0_0_15px_rgba(255,215,0,0.8)]"></div><h3 class="flex-1 text-2xl font-bold tracking-wider text-white">气象预警</h3><button class="floating-panel-close-btn floating-panel-close-btn--inline" type="button" title="关闭气象预警" @click="emit('close')">✕</button></div>
                <div class="mb-4 grid grid-cols-3 gap-2 text-xs"><div class="border border-cyan-500/20 bg-slate-950/45 p-2 text-slate-400">全部<strong class="mt-1 block text-lg text-cyan-100">{{ stats.total ?? 0 }}</strong></div><div class="border border-amber-500/20 bg-slate-950/45 p-2 text-slate-400">生效中<strong class="mt-1 block text-lg text-amber-100">{{ stats.active ?? 0 }}</strong></div><div class="border border-rose-500/20 bg-slate-950/45 p-2 text-slate-400">严重<strong class="mt-1 block text-lg text-rose-100">{{ stats.critical ?? 0 }}</strong></div></div>
                <div class="mb-3 grid grid-cols-3 gap-2"><select v-model="filters.range" class="border border-slate-700 bg-slate-950/70 px-2 py-2 text-xs text-slate-200"><option value="">全部时段</option><option value="12h">未来12h</option><option value="7d">未来7天</option><option value="15d">未来15天</option></select><select v-model="filters.severity" class="border border-slate-700 bg-slate-950/70 px-2 py-2 text-xs text-slate-200"><option value="">全部等级</option><option value="WARNING">预警</option><option value="CRITICAL">严重</option></select><select v-model="filters.status" class="border border-slate-700 bg-slate-950/70 px-2 py-2 text-xs text-slate-200"><option value="">全部状态</option><option value="ACTIVE">生效中</option><option value="RESOLVED">已解除</option></select></div>
                <div v-if="errorMessage" class="mb-3 border border-rose-500/35 bg-rose-950/30 p-3 text-sm text-rose-100">{{ errorMessage }}</div>
                <div class="mb-2 flex items-center justify-between"><span class="text-sm font-bold text-cyan-200">预警记录</span><button class="text-xs font-bold text-cyan-300 hover:text-white" type="button" @click="loadWarnings">刷新</button></div>
                <div class="custom-scrollbar min-h-0 flex-1 space-y-2 overflow-y-auto pr-2"><div v-if="loading" class="flex h-full items-center justify-center text-sm text-slate-400">正在加载预警记录...</div><button v-for="item in warnings" :key="item.id" type="button" :class="['w-full border p-3 text-left transition-all', item.id === selectedWarning?.id ? 'border-cyan-300/70 bg-cyan-950/45' : 'border-slate-700/70 bg-slate-950/35 hover:border-cyan-500/45']" @click="selectWarning(item)"><div class="flex items-start justify-between gap-2"><div class="min-w-0"><div class="truncate text-sm font-bold text-white">{{ item.warningCode }}</div><div class="mt-1 truncate text-xs text-slate-400">{{ item.regionName }} · {{ rangeText(item.timeRange) }}</div></div><span :class="['border px-2 py-0.5 text-xs font-bold', severityClass(item.severity)]">{{ severityText(item.severity) }}</span></div><div class="mt-2 border-t border-slate-700/60 pt-2 text-xs text-slate-300">{{ item.warningMessage }}</div><div class="mt-1 text-xs text-slate-500">{{ item.triggerType }} · {{ formatTime(item.createdAt) }}</div></button><div v-if="!loading && !warnings.length" class="flex h-36 items-center justify-center border border-dashed border-slate-700/50 text-sm text-slate-500">暂无符合条件的气象预警</div></div>
            </section>
            </div>

            <div class="pointer-events-none absolute right-6 top-36 w-[29rem] max-h-[54.5rem]">
            <section class="tech-panel-enhanced pointer-events-auto relative flex max-h-[54.5rem] flex-col overflow-hidden p-5" style="clip-path: polygon(0 0,92% 0,100% 7%,100% 100%,0 100%);"><div class="absolute left-0 top-0 h-[2px] w-full animate-pulse bg-gradient-to-r from-transparent via-cyan-400 to-transparent"></div><div class="corner-decoration corner-bl scale-125"></div><div class="corner-decoration corner-br scale-125"></div><div class="mb-3 flex items-start justify-between border-b-2 border-cyan-500/40 pb-3"><div><div class="text-xl font-bold text-white">{{ selectedWarning?.warningCode || '预警详情' }}</div><div class="mt-1 text-xs text-slate-400">{{ selectedWarning?.regionName || '请选择左侧预警记录' }}</div></div><button v-if="selectedWarning" class="border border-cyan-500/45 bg-cyan-950/45 px-3 py-1.5 text-xs font-bold text-cyan-100 hover:bg-cyan-500 hover:text-slate-950" type="button" @click="download">下载报文</button></div><div v-if="detailLoading" class="flex flex-1 items-center justify-center text-sm text-slate-400">正在加载预警详情...</div><template v-else-if="selectedWarning"><div class="mb-3 grid grid-cols-2 gap-2 text-xs"><div class="border border-slate-700/60 bg-slate-950/35 p-3 text-slate-400">预警等级<strong :class="['mt-1 block text-base', severityClass(selectedWarning.severity)]">{{ severityText(selectedWarning.severity) }}</strong></div><div class="border border-slate-700/60 bg-slate-950/35 p-3 text-slate-400">预警状态<strong class="mt-1 block text-base text-cyan-100">{{ statusText(selectedWarning.status) }}</strong></div></div><div class="mb-3 text-sm leading-6 text-slate-200">{{ selectedWarning.warningMessage }}</div><div class="mb-3 border-y border-cyan-500/20 py-3"><div class="mb-2 text-sm font-bold text-cyan-200">触发指标</div><div class="space-y-1 text-xs text-slate-300"><div v-for="trigger in selectedWarning.triggerDetail || []" :key="`${trigger.type}-${trigger.value}`">{{ trigger.type }}：{{ trigger.value }} {{ trigger.unit }} / 阈值 {{ trigger.threshold }} {{ trigger.unit }}</div></div></div><div class="custom-scrollbar min-h-0 flex-1 overflow-y-auto whitespace-pre-wrap pr-2 text-sm leading-7 text-slate-200">{{ selectedWarning.bulletinText || '暂无预警报文正文' }}</div></template><div v-else class="flex flex-1 items-center justify-center border border-dashed border-slate-700/50 text-sm text-slate-500">请选择一条预警记录</div></section>
            </div>

            <div class="pointer-events-none absolute bottom-16 left-[31rem] right-[31rem] h-[19rem]">
            <section class="tech-panel-enhanced pointer-events-auto relative h-full overflow-hidden p-4"><div class="absolute left-0 top-0 h-[2px] w-full bg-gradient-to-r from-transparent via-cyan-400 to-transparent"></div><div class="mb-3 flex items-center justify-between"><div><div class="text-lg font-bold text-white">预警触发预报快照</div><div class="mt-1 text-xs text-slate-400">{{ selectedWarning?.regionName || '--' }} · 触发时保存的风浪流预测数据</div></div></div><div class="relative h-[14rem] w-full"><div ref="chartRef" class="h-full w-full"></div><div v-if="detailLoading" class="absolute inset-0 flex items-center justify-center bg-slate-950/55 text-sm text-slate-300">正在读取快照...</div></div></section>
            </div>
        </div>
    </transition>
</template>

<script setup>
import { nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue';
import * as echarts from 'echarts';
import { downloadWeatherWarningBulletin, fetchWeatherWarningDetail, fetchWeatherWarnings, fetchWeatherWarningStats } from '../api/forecastWarningBuoy.js';

const props = defineProps({ show: Boolean }); const emit = defineEmits(['close']);
const stats = ref({}); const warnings = ref([]); const selectedWarning = ref(null); const loading = ref(false); const detailLoading = ref(false); const errorMessage = ref(''); const filters = reactive({ range: '', severity: '', status: '' }); const chartRef = ref(null); let chart = null;
const severityText = (value) => ({ INFO: '提示', WARNING: '预警', CRITICAL: '严重' }[value] || value || '--'); const statusText = (value) => ({ ACTIVE: '生效中', RESOLVED: '已解除', EXPIRED: '已过期' }[value] || value || '--'); const rangeText = (value) => ({ '12h': '未来12h', '7d': '未来7天', '15d': '未来15天' }[value] || '--'); const severityClass = (value) => ({ INFO: 'border-cyan-500/45 bg-cyan-950/35 text-cyan-100', WARNING: 'border-amber-400/45 bg-amber-950/35 text-amber-100', CRITICAL: 'border-rose-400/45 bg-rose-950/35 text-rose-100' }[value] || 'border-slate-600 text-slate-300'); const formatTime = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '--' : date.toLocaleString('zh-CN', { hour12: false, month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }); };
const snapshotSeries = () => Array.isArray(selectedWarning.value?.forecastData?.series) ? selectedWarning.value.forecastData.series : [];
const renderChart = async () => { await nextTick(); if (!props.show || !chartRef.value) return; if (!chart || chart.getDom() !== chartRef.value) { chart?.dispose(); chart = echarts.init(chartRef.value); } const records = snapshotSeries(); chart.setOption({ backgroundColor: 'transparent', color: ['#22d3ee', '#facc15', '#a78bfa'], tooltip: { trigger: 'axis' }, legend: { top: 0, textStyle: { color: '#cbd5e1' }, data: ['风速', '浪高', '流速'] }, grid: { left: 44, right: 50, top: 34, bottom: 36 }, xAxis: { type: 'category', data: records.map((item) => formatTime(item.forecastTime || item.forecastDate)), axisLabel: { color: '#94a3b8', fontSize: 10, hideOverlap: true }, axisLine: { lineStyle: { color: '#334155' } } }, yAxis: [{ type: 'value', name: 'm/s', axisLabel: { color: '#94a3b8' }, nameTextStyle: { color: '#94a3b8' }, splitLine: { lineStyle: { color: 'rgba(71,85,105,.35)' } } }, { type: 'value', name: 'm', position: 'right', axisLabel: { color: '#94a3b8' }, nameTextStyle: { color: '#94a3b8' }, splitLine: { show: false } }], series: [{ name: '风速', type: 'line', smooth: true, showSymbol: false, data: records.map((item) => item.windSpeedMax ?? item.windSpeedAvg) }, { name: '浪高', type: 'line', smooth: true, yAxisIndex: 1, showSymbol: false, data: records.map((item) => item.waveHeightMax ?? item.waveHeightAvg) }, { name: '流速', type: 'line', smooth: true, showSymbol: false, data: records.map((item) => item.currentSpeedMax ?? item.currentSpeedAvg) }] }, true); };
const selectWarning = async (item) => { detailLoading.value = true; try { selectedWarning.value = await fetchWeatherWarningDetail(item.id); } catch (error) { errorMessage.value = `预警详情加载失败：${error.message}`; selectedWarning.value = item; } finally { detailLoading.value = false; await nextTick(); await renderChart(); } };
const loadWarnings = async () => { loading.value = true; errorMessage.value = ''; try { const [nextStats, response] = await Promise.all([fetchWeatherWarningStats(), fetchWeatherWarnings({ ...filters, page: 1, pageSize: 50 })]); stats.value = nextStats || {}; warnings.value = response?.items || []; const current = warnings.value.find((item) => item.id === selectedWarning.value?.id) || warnings.value[0]; if (current) await selectWarning(current); else { selectedWarning.value = null; await renderChart(); } } catch (error) { errorMessage.value = `气象预警加载失败：${error.message}`; } finally { loading.value = false; } };
const download = async () => { try { await downloadWeatherWarningBulletin(selectedWarning.value.id, selectedWarning.value.warningCode); } catch (error) { errorMessage.value = `预警报文下载失败：${error.message}`; } };
const handleUpdate = () => { if (props.show) loadWarnings(); };
const resizeChart = () => chart?.resize();
watch(() => props.show, (visible) => { if (visible) loadWarnings(); }); watch(filters, () => { if (props.show) loadWarnings(); }); watch(selectedWarning, renderChart);
onMounted(() => { window.addEventListener('resize', resizeChart); window.addEventListener('weather-warning-updated', handleUpdate); if (props.show) loadWarnings(); }); onBeforeUnmount(() => { chart?.dispose(); window.removeEventListener('resize', resizeChart); window.removeEventListener('weather-warning-updated', handleUpdate); });
</script>
